---
name: pypi-publish
description: Upload Python distribution packages to PyPI
inputs:
  user:
    description: PyPI user
    required: false
    default: __token__
  password:
    description: Password for your PyPI user or an access token
    required: true
  repository_url:
    description: The repository URL to use
    required: false
  packages_dir:
    description: The target directory for distribution
    required: false
    default: dist
  verify_metadata:
    description: Check metadata before uploading
    required: false
    default: 'true'
  skip_existing:
    description: >-
      Do not fail if a Python package distribution
      exists in the target package index
    required: false
    default: 'false'
  verbose:
    description: Show verbose output.
    required: false
    default: 'false'
  print_hash:
    description: Show hash values of files to be uploaded
    required: false
    default: 'false'
branding:
  color: yellow
  icon: upload-cloud
runs:
  using: docker
  image: Dockerfile
  args:
  - ${{ inputs.user }}
  - ${{ inputs.password }}
  - ${{ inputs.repository_url }}
  - ${{ inputs.packages_dir }}
  - ${{ inputs.verify_metadata }}
  - ${{ inputs.skip_existing }}
  - ${{ inputs.verbose }}
  - ${{ inputs.print_hash }}
